{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"kind":"text","text":" = "},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}],"externalID":"s:7FlowKit20AsyncThrowingSubjectV7Failurea","title":"AsyncThrowingSubject.Failure","roleHeading":"Type Alias","navigatorTitle":[{"text":"Failure","kind":"identifier"}],"role":"symbol","modules":[{"name":"FlowKit"}],"symbolKind":"typealias"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flowkit\/asyncthrowingsubject\/failure"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"references":{"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject","title":"AsyncThrowingSubject","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AsyncThrowingSubject"}],"url":"\/documentation\/flowkit\/asyncthrowingsubject","abstract":[{"type":"text","text":"A subject that allows for asynchronously sending values or terminating with an error."},{"type":"text","text":" "},{"code":"AsyncThrowingSubject","type":"codeVoice"},{"text":" acts as a bridge between imperative code and asynchronous code, enabling","type":"text"},{"text":" ","type":"text"},{"text":"you to send values to an ","type":"text"},{"type":"codeVoice","code":"AsyncSequence"},{"text":" consumer while handling potential errors gracefully.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"AsyncThrowingSubject","kind":"identifier"}]},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject/Failure":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}],"url":"\/documentation\/flowkit\/asyncthrowingsubject\/failure","role":"symbol","navigatorTitle":[{"text":"Failure","kind":"identifier"}],"type":"topic","title":"AsyncThrowingSubject.Failure","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure","abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}]},"doc://flowkit.FlowKit/documentation/FlowKit":{"url":"\/documentation\/flowkit","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","title":"FlowKit","kind":"symbol","role":"collection","abstract":[],"type":"topic"}}}