{"metadata":{"symbolKind":"typealias","roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"Failure"}],"modules":[{"name":"FlowKit"}],"externalID":"s:7FlowKit20AsyncThrowingSubjectV7Failurea","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"}],"title":"AsyncThrowingSubject.Failure"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"},{"text":" = ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flowkit\/asyncthrowingsubject\/failure"]}],"abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure"},"sections":[],"references":{"doc://flowkit.FlowKit/documentation/FlowKit":{"identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","type":"topic","kind":"symbol","title":"FlowKit","url":"\/documentation\/flowkit","abstract":[],"role":"collection"},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject":{"type":"topic","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject","kind":"symbol","title":"AsyncThrowingSubject","navigatorTitle":[{"kind":"identifier","text":"AsyncThrowingSubject"}],"url":"\/documentation\/flowkit\/asyncthrowingsubject","role":"symbol","abstract":[{"text":"A subject that allows for asynchronously sending values or terminating with an error.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"AsyncThrowingSubject"},{"text":" acts as a bridge between imperative code and asynchronous code, enabling","type":"text"},{"text":" ","type":"text"},{"text":"you to send values to an ","type":"text"},{"code":"AsyncSequence","type":"codeVoice"},{"type":"text","text":" consumer while handling potential errors gracefully."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AsyncThrowingSubject"}]},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject/Failure":{"abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"role":"symbol","kind":"symbol","url":"\/documentation\/flowkit\/asyncthrowingsubject\/failure","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}],"navigatorTitle":[{"text":"Failure","kind":"identifier"}],"title":"AsyncThrowingSubject.Failure","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure","type":"topic"}}}