{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"Failure","kind":"identifier"}],"role":"symbol","modules":[{"name":"FlowKit"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"}],"title":"AsyncThrowingSubject.Failure","symbolKind":"typealias","externalID":"s:7FlowKit20AsyncThrowingSubjectV7Failurea","roleHeading":"Type Alias"},"hierarchy":{"paths":[["doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"]]},"abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flowkit\/asyncthrowingsubject\/failure"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"text":" = ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AsyncThrowingSubject"}],"identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AsyncThrowingSubject"}],"url":"\/documentation\/flowkit\/asyncthrowingsubject","abstract":[{"text":"A subject that allows for asynchronously sending values or terminating with an error.","type":"text"},{"type":"text","text":" "},{"code":"AsyncThrowingSubject","type":"codeVoice"},{"text":" acts as a bridge between imperative code and asynchronous code, enabling","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"you to send values to an "},{"code":"AsyncSequence","type":"codeVoice"},{"type":"text","text":" consumer while handling potential errors gracefully."}],"title":"AsyncThrowingSubject","type":"topic"},"doc://flowkit.FlowKit/documentation/FlowKit":{"abstract":[],"identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","type":"topic","title":"FlowKit","url":"\/documentation\/flowkit","kind":"symbol","role":"collection"},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject/Failure":{"title":"AsyncThrowingSubject.Failure","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"role":"symbol","url":"\/documentation\/flowkit\/asyncthrowingsubject\/failure","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure","kind":"symbol","navigatorTitle":[{"text":"Failure","kind":"identifier"}]}}}