{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"text":" = ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flowkit\/asyncthrowingsubject\/failure"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"The type of error that can terminate the sequence.","type":"text"}],"metadata":{"symbolKind":"typealias","externalID":"s:7FlowKit20AsyncThrowingSubjectV7Failurea","roleHeading":"Type Alias","navigatorTitle":[{"text":"Failure","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Failure"}],"role":"symbol","title":"AsyncThrowingSubject.Failure","modules":[{"name":"FlowKit"}]},"references":{"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject":{"type":"topic","role":"symbol","kind":"symbol","title":"AsyncThrowingSubject","url":"\/documentation\/flowkit\/asyncthrowingsubject","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AsyncThrowingSubject"}],"navigatorTitle":[{"kind":"identifier","text":"AsyncThrowingSubject"}],"abstract":[{"type":"text","text":"A subject that allows for asynchronously sending values or terminating with an error."},{"text":" ","type":"text"},{"code":"AsyncThrowingSubject","type":"codeVoice"},{"text":" acts as a bridge between imperative code and asynchronous code, enabling","type":"text"},{"text":" ","type":"text"},{"text":"you to send values to an ","type":"text"},{"type":"codeVoice","code":"AsyncSequence"},{"type":"text","text":" consumer while handling potential errors gracefully."}]},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject/Failure":{"type":"topic","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure","url":"\/documentation\/flowkit\/asyncthrowingsubject\/failure","abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"role":"symbol","navigatorTitle":[{"text":"Failure","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}],"title":"AsyncThrowingSubject.Failure"},"doc://flowkit.FlowKit/documentation/FlowKit":{"url":"\/documentation\/flowkit","title":"FlowKit","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","kind":"symbol"}}}